### ISSUE TITLE
openvpn3-autoload with google authentificator code

### ISSUE THREAD

**Issue by 221V** [OpenVPN/openvpn3-linux#109]
hello!
i read [docs](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/openvpn3-autoload.md), [docs](https://openvpn.net/vpn-server-resources/connecting-to-access-server-with-linux/), [docs](https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux) and [docs](https://openvpn.net/blog/openvpn-3-linux-and-auth-user-pass/), and have one question --  
there are any way to use openvpn3-autoload with google authentificator ?

i.e. when connect - type only google authentificator code,
not full - username, pass, google authentificator code

linux - ubuntu 20.04

thank you!

**Comment by dsommers** [comment]
No, it is not.  Consider it a security feature, as you want to be sure authentication requiring a users credentials is actually present.

If you do want to log in automatically, you should use plain certificate based authentication. Adding username/password + OTP on top of that doesn't really give you an advantage.

That said, both `openvpn3-autoload` and `openvpn2` are just plain Python 3 scripts.  And there are [more examples](https://github.com/OpenVPN/openvpn3-linux/tree/master/src/tests/python/) in the source tree. So it's not impossible, just something we do not want to support officially - because it doesn't give much of an advantage over plain certificate based authentication when trying to automate credentials passing.
