### ISSUE TITLE
openvpn3 Auto logon not working 

### ISSUE THREAD

**Issue by fazalmf** [OpenVPN/openvpn3-linux#18]
tried add - auth-user-pass auth.txt in configuration file  but still connection failed 
Session path: /net/openvpn/v3/sessions/e3e25ec5s478es40e0sb894s67967d978c99
session-start: ** ERROR ** Failed to start session

same configuration file woks without auth.txt ( manually need to pass the credentials)
openvpn3 session-start --config /home/XXXX/openvpn/XXXX.ovpn
Using configuration profile from file: /home/XXXX/openvpn/XXX.ovpn
Session path: /net/openvpn/v3/sessions/2d0b8583sbbc4s48aasaa09sa9012dd8da4a
Auth User name: 
Auth Password:
Connected

**Comment by dsommers** [comment]
OpenVPN 3 Linux does not support --auth-user-pass with saved credentials like OpenVPN 2.x.  I have not yet decided if we should support it in this way, or use a different approach for it.  Storing user credentials is generally not recommended.

You should be able to achieve what you want using the openvpn3-autoload utility which will be able to handle this scenario.  This approach saves the credentials only for the session startup in the OpenVPN 3 backend services.  You need to save the OpenVPN configuration profile in it's own directory (for example: `client.conf`) and have a autoload configuration file in the same directory (`client.autoload`).  The contents of this additonal file is documented in the [openvpn3-autload(8)](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst) man page.  You need to set `"autostart": true` for this to work.  With this configured, you can start the configuration using `openvpn3-autoload --directory /path/to/openvpn/profile`.

**Comment by dsommers** [comment]
We have just released a workaround document on this feature: https://openvpn.net/openvpn-3-linux-and-auth-user-pass/

**Comment by fazalmf** [comment]
Good to know . thank you

**Comment by MaxWS** [comment]
Thanks

**Comment by bipinmdr07** [comment]
Sadly but couldn't find any documentation on configuring the autoload with ovpn file which has `static-challenge` in it. Anything we can do with this @dsommers ?

**Comment by dsommers** [comment]
@bipinmdr07 Nope. That' defeats the purpose of a the static-challenge.  That is typically used with OTP tokens, so that value is not static thus not much useful to put into a configuration.

That said, it is possible to write your own script doing this magic for you.  The OpenVPN 3 Linux project ships with a Python module which is used by [`openvpn2`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn2), [`openvpn3-autoload`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn3-autoload) and [`openvpn3-systemd`](https://github.com/OpenVPN/openvpn3-linux/blob/master/distro/systemd/openvpn3-systemd).  But built-in support for automated OTP codes is not something we consider for inclusion into this project.  Hosts requiring automatic connection without user interaction should normally use certificate-only authentication, which is already a very strong authentication method.
