### ISSUE TITLE
Remove multiple configs having same name

### ISSUE THREAD

**Issue by rajeshisnepali** [OpenVPN/openvpn3-linux#21]
I was doing the [openvpn3-autoload](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-autoload.8.rst) test and ended up with multiple same config name. 

![image](https://user-images.githubusercontent.com/23610013/92997656-895e8900-f534-11ea-900c-68ef4daaed61.png)

➜   `openvpn3 config-remove -c openvpn-in* --force`
config-remove: ** ERROR ** No configuration profiles found
➜   `openvpn3 config-remove -c openvpn-in --force `
config-remove: ** ERROR ** More than one configuration profile was found with the given name

I tried doing above but had no success.  
 Isn't there any hack to remove all the same configs so that I don't have to manually remove each of them.

**Comment by dsommers** [comment]
One alternative is to stop the `openvpn3-service-configmgr` process.  Configuration profiles imported by `openvpn3-autoload` is kept in memory during the lifetime of the Configuration Manager (`openvpn3-service-configmgr`).

Another approach is to write a Python 3 script which uses the `openvpn3` module which provides the [`openvpn3.ConfigManager`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn3/ConfigManager.py) class.  This provides a `LookupConfigName()` method which returns a list of `Configuration` objects for each configuration profile matching the given name.  Calling the `Remove()` method in each of these objects will do the trick.

Just beware, the `openvpn3-autoload` utility is not a proper replacement for `openvpn3 session-start`, it only provides a solution to situations where you want to automatically load VPN profiles and optionally start them.  Typically during boot or login situations.  But it can be run manually as well, which is why the manual run approach is considered a workaround for the `--auth-user-pass` with credentials saved in a file.

You may also write your own utility doing similar things, using the D-Bus API provied by OpenVPN 3 Linux.  The [`openvpn2`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn2) and [`openvpn3-autoload`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn3-autoload) programs are just Python scripts making use of that API.  There is also an [`openvpn3.SessionManager`](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/python/openvpn3/SessionManager.py) class, which can be used to start VPN sessions and provide user credentials programmatically.

**Comment by dsommers** [comment]
The complete D-Bus interface is documented here: [OpenVPN 3 Linux Client - D-Bus overview](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/dbus/dbus-overview.md)

**Comment by dsommers** [comment]
A very quick Python script may help ...  this script is untested, so may have some minor issues - but the overall concept should work.

```python
import dbus
import openvpn3

cfgmgr = openvpn3.ConfigurationManager(dbus.SystemBus())
for cfg_path in cfgmgr.LookupConfigName('openvpn-in'):
    profile = cfgmgr.Retrieve(cfg_path)
    print("Removing configuration %s ... Path: %s" % (profile.GetConfigName(), profile.GetPath()))
    # profile.Remove()
```

Remove the `#` in front of the last `profile.Remove()` line to really remove the configuration profile.
