### ISSUE TITLE
openvpn3 8a13d1b8d88748ae session fails to start, but starts when calling a second time

### ISSUE THREAD

**Issue by remanifest** [OpenVPN/openvpn3-linux#259]
Sometimes, when I try to start a session using the call `openvpn3 session-start --config ~/Documents/openvpn/vpn.ovpn`, I get this messge:

```
[DBus::Connection] Connection flush failed The connection is closed
---- [SessionManager::Proxy] Failed to start new tunnel
```
However, when I simply run the call again, the session starts successfully and prompts me for authentication. I'm not sure if this is something to do with my config, if there's something I'm not doing, or if the services just aren't "waiting" long enough, but it's odd that this is repeatable.

Happy to provide any logs that may be beneficial.

Thank you for all of your work on migrating openvpn3 to this point. I know it was a massive undertaking.

**Comment by dsommers** [comment]
Thanks for testing.  IIRC, you're using the Arch builds, right?

It would be good if you could try testing the latest git master in both openvpn3-linux and gdbuspp ....  Our QA spotted the same behaviour and I believe that should be fixed by.  I pushed out the latest branches late Friday.

I see @rzvncj has already updated the `gdbuspp-git` repo.  The `openvpn3-git` is not, so perhaps updating the `PKGBUILD` @rzvncj provided in #171 will get you up-to-date quicker.  There is something like 5-6 bugs fixed in the change-span `8a13d1b..b387eb0d4` (from `openvpn3-git` version to latest git master).

**Comment by dsommers** [comment]
Ahh! I spot the detail in the error now. Sorry that took some time. I believe that's been fixed. I unfortunately didn't manage to push it out before heading out of the office today.  I'll get it out ASAP tomorrow, even though I'll be mostly offline tomorrow. Worst case on Wednesday, and then I believe QA has also managed to test this issue too.

Workaround is basically to first import the profile with `openvpn3 config-import`.  If you use `--persistent`, you don't need to do it more than once.

**Comment by dsommers** [comment]
The detail is this line:

      Connection flush failed The connection is closed

If you check the line above this one and compare it with the successful runs, you'll see the second attempt will use a preloaded configuration profile. But that is imported with a `single-use` flag set, so it only works once.

That's why using `openvpn3 config-import` first works.

**Comment by dsommers** [comment]
I've just pushed out an updated git master to the public ... I'm pretty sure [commit 1ea1c445171bb81f](https://codeberg.org/OpenVPN/openvpn3-linux/commit/1ea1c445171bb81f5d8dd22791e43f1db6880515) fixes your issue.

**Comment by remanifest** [comment]
> I've just pushed out an updated git master to the public ... I'm pretty sure [commit 1ea1c445171bb81f](https://codeberg.org/OpenVPN/openvpn3-linux/commit/1ea1c445171bb81f5d8dd22791e43f1db6880515) fixes your issue.

That did the trick. Thank you!

**Comment by dsommers** [comment]
Thanks for testing and the feedback!  Closing it now.
