### ISSUE TITLE
Ubuntu issues with libcap-ng-dev

### ISSUE THREAD

**Issue by benyanke** [OpenVPN/openvpn3-linux#3]
The readme states that to build, the following packages need to be installed from apt:

`build-essential git pkg-config autoconf autoconf-archive libglib2.0-dev libjsoncpp-dev uuid-dev libmbedtls-dev liblz4-dev libcapng-dev`

The package `libcapng-dev` is not found, but `libcap-ng-dev` is, and allows the build to continue.

**Comment by dsommers** [comment]
Thanks for the report.  As mentioned in the pull-request, it's a silly typo which got spread to all apt-get/dnf/yum install lines. So if the pull-req can be updated to cover all `libcapng` occurrences to `libcap-ng`, I'd appreciate that.

Normally I want contributions to be sent to the openvpn-devel mailing list, but since this is a simple and plain documentation fix I'll accept github pull-requests.  The long-term tracking capability is much more important for code changes than small and simple documentation issues.

**Comment by benyanke** [comment]
`So if the pull-req can be updated to cover all libcapng occurrences to libcap-ng, I'd appreciate that.`

That's odd - the one I updated is the only one that broke. Should I still update?

**Comment by dsommers** [comment]
Yes, it is wrong on all distros.  The proper package name is `libcap-ng` and the development headers are in `-dev` for Debian/Ubuntu and `-devel` for RHEL/Fedora.

**Comment by benyanke** [comment]
My mistake - thought you meant others in the ubuntu/debian line. Will update.

**Comment by benyanke** [comment]
Done now - and moving discussion to PR so we don't have two parallel discussions going on.
