### ISSUE TITLE
Raspbian GNU/Linux support (armv7l/armhf 32-bit)

### ISSUE THREAD

**Issue by SofoklisKat** [OpenVPN/openvpn3-linux#49]
Is openvpn3 client supported in Raspbian GNU/Linux  >?

**Comment by schwabe** [comment]
We do not build packages for it but self building it on Raspian should work. Note that we provide images for Ubuntu on ARM64, which also runs on Raspian

**Comment by SofoklisKat** [comment]
Thanks for the quick response,

I tried to build it in the Rpi with the following 2 methods but both failed. 

When I build it in raspberry pi through in the default Rasbian Image I receive the following error.

In file included from src/configmgr/configmgr.hpp:36,
                 from src/configmgr/openvpn3-service-configmgr.cpp:23:
./src/dbus/object-property.hpp:127:67: error: call of overloaded ‘GetVariantValue<long int>(GVariant*&)’ is ambiguous

When I build it in raspberry pi through an Ubuntu Armv7 Image I receive the following error.

In file included from src/configmgr/configmgr.hpp:36:0,
                 from src/configmgr/openvpn3-service-configmgr.cpp:23:

./src/dbus/object-property.hpp:115:48: error: call of overloaded 'GetDBusDataType<long int>()' is ambiguous
                 ? GLibUtils::GetDBusDataType<T>()


Any thoughts  ?

**Comment by dsommers** [comment]
Which compiler and which version of it do you use?

**Comment by schwabe** [comment]
@dsommers did we ever fix the compile on certain 32 bit architectures bug?

**Comment by dsommers** [comment]
@schwabe I believe we did, bit from a quick glance this looks like a different issue, ås it is triggered by a template in dbus/object-property.hpp this time. Last time it was related to different int size interpretations in glibutils.hpp

**Comment by dsommers** [comment]
With the v14_beta release, which is going out today, we do support arm64 platforms.  The 32-bit platforms in general are currently not supported, and the armv7l architecture is a 32-bit platform.

**Comment by dsommers** [comment]
@bibiefart It's not that easy.  We need a proper solution for handling integer data types in [src/dbus/glibutils.hpp](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/dbus/glibutils.hpp) on 32 bit systems, which currently conflicts with 64 bit systems.  First functions to get fixed is `GLibUtils::GetDBusDataType()` and `GLibUtils::GetVariantValu()`, but I suspect it is also needed to fix `GlibUtils::ExtractValue()`.

**Comment by M00N-MAN** [comment]
Hi all,

why just not use

```
template<> inline const char* GetDBusDataType<int>()               {return "i";}
template<> inline const char* GetDBusDataType<long>()            {return "i";}
template<> inline int                GetVariantValue<int>(GVariant *v){return g_variant_get_int32(v);}
template<> inline long             GetVariantValue<long>(GVariant *v){return g_variant_get_int32(v);}
```

???

otherwise with this templates in glibutils.hpp compilers are saying that GetDBusDataType(); and GetDBusDataType<T>() are ambiguos... because it is obvious that GetDBusDataType<T/*int or long*/>() wont't be used as definition of this declaration template<typename T> inline const char* GetDBusDataType(); because there should be template<> specialiation, but not another function.

same with GetVariantValue()

don't you think so?

please share the contr-cases to take attention to.

**Comment by TheReelDill** [comment]
Any plans to move this forward or is 32 bit dead for OpenVPN3?

**Comment by dsommers** [comment]
To be honest, in general 32 bit OSes is not high up on the priority list at all.  In Linux 64-bit has had a huge focus the last 15+ years, and even embedded devices are now commonly on 64 bit architectures as well.

In addition, we are exploring an alternative D-Bus implementation to glib2 -which riddles us with various issues and challenges.  The new alternative implementation will be a pure C++ implementation and not a C library wrapped into C++ classes.  I suspect many of these issues might be better solved with the new implementation.  However, we don't have any ETA for that yet.  But it will get a lot more focus after the first stable version has been released (which is planned to be either v20 or v21, depending on issues found in the just released v19_beta).

**Comment by dsommers** [comment]
Closing this.  The reasons for using a 32-bit RaspberryPi these days is fairly low.  All RaspberryPi's since model 3 supports 64-bit OSes.  This is not something we've had time to investigate further in many years, and the requests for 32-bit platforms is not something which has been required by many users at all.

I'm closing this now.  If someone in the community is willing to invest time to support 32-bit OSes, we can review patches.  But we will not put efforts into 32-bit platforms on our end anytime soon.
