### ISSUE TITLE
resolv.conf overwrite by default

### ISSUE THREAD

**Issue by j4m3s-s** [OpenVPN/openvpn3-linux#51]
By default I use some custom DNS resolvers. But Openvpn3 when activated, overwrite my DNS servers with its preferred one.
I wish to avoid leaking my DNS queries by default, is it possible ?

**Comment by dsommers** [comment]
You can import your configuration profile using `openvpn3 config-import --persistent --config $CONFIG_FILE --name myvpn`  and then disable the DNS configuration from the server with `openvpn3 config-manage --config myvpn --dns-setup-disabled true`.  To start the VPN profile, use `openvpn3 session-start --config myvpn`.

In this example the import is done using `--persistent`.  This means the configuration file is saved to disk in a file directory only accessible to the `openvpn3-service-configmgr` (Configuration Manager) service.  That also means the settings done using `openvpn3 config-manage` is preserved between boots.

If you use `openvpn2`, you can add `--profile-override dns-setup-disabled true`.  But this might be a bit more tedious approach in the long run for profiles you use a lot.  I recommend using the `openvpn3` front-end.

Please let me know if this works for you.

**Comment by j4m3s-s** [comment]
This seems to work, thanks !

Do you want me to write some documentation about it ? Or maybe there is and I've missed it. If it's not the case, should I open a new issue ?

**Comment by dsommers** [comment]
Great!

In regards to documentation, we don't have a "what to do if ...." documentation.  But the `dns-setup-disabled` feature is documented in the man pages for both [openvpn3 config-manage](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn3-config-manage.1.rst) and [openvpn2](https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn2.1.rst)

 If you want, it might be a good idea add an "OpenVPN 3 Tips and Tricks" wiki page (https://community.openvpn.net/openvpn/wiki/ ).  That would be a good place to collect such documentation.

Since this is issue is resolved and working with the `dns-setup-disabled` feature, I'm closing this ticket now.
