### ISSUE TITLE
Using openvpn3 client on a production machine?

### ISSUE THREAD

**Issue by Danrancan** [OpenVPN/openvpn3-linux#67]
I am tunneling an email server to an Amazon AWS openvpn-as instance, in order to get proper PTR records from amazon, as my ISP won't provide them. So far, openvpn3 has worked successfully using the autolaoder, and my email server/web server are tunneling successfully to to the AWS Instance. I do not mind if the tunnel goes down from time to time as long as it reconnects (which it has been doing) and goes back up eventually. Also, I really don't need any of the features aside from the tunnel to obtain the AWS IP address.

With the above being noted, my quick question is, for this use case... 
1. How safe is this and how close to production ready is openvpn3? 
2. For my intents and purposes, should this beta version of openvpn3 be suitable for a production environment running as a client on a live server? 

Thanks for any help and advice.

**Comment by dsommers** [comment]
First of all, we are getting closer to remove the beta-tag.  There are still a few minor things we would like to solve and we need to switch the OpenVPN 3 Core library from the development version (which has currently more requested features) to an official release tag.  Once the official release tag containing the features needed, we are pretty much close to a the first stable release.

That said, I am running OpenVPN 3 Linux in production environments without any issues - with a setup quite similar to yours.  The host was configured with the v1_beta release and has since then been upgraded successfully.  In addition, I'm running this client every day for my work (which is also closely tied to OpenVPN 3 Linux development).

I have no concerns running v15_beta in production.  But each upgrade may impose a higher risk until we have reached stable releases.  However, I do try to resolve critical issues appearing in new releases as quickly as I can (which is why there was quite a short time between v14_beta and v15_beta; less than 1 week).  And I do try to ensure downgrades are within reasonable reach.

**Comment by Danrancan** [comment]
This answers everything I asked for and more! Thank you for being such an active and informative developer! It is very much appreciated!
