### ISSUE TITLE
Describe / provide tutorial for creating a conf file while using the command line client

### ISSUE THREAD

**Issue by aino-gautam** [OpenVPN/openvpn3-linux#93]
Though I easily found tons of material around installing the client, all connect command rely on a configuration profile and there is no documentation anywhere ( atleast I couldn't find ) about the format of the conf file or how to create it.

**Comment by dsommers** [comment]
Installing the OpenVPN 3 Linux client is of very little use unless there is a server side you want to connect to.  Since this project so far has provided only the client side features, it expects the server side provider to provide client configurations.

The complete OpenVPN 2.x options are covered in the [man page](https://build.openvpn.net/man/openvpn-2.5/openvpn.8.html) for it.  In addition there i the "[Getting Started With OpenVPN](https://community.openvpn.net/openvpn/wiki/GettingStartedwithOVPN)" how-to, available on the [OpenVPN community wiki](https://community.openvpn.net/openvpn/wiki/).

There exists good books as we, like "[OpenVPN 2 Cookbook](https://www.packtpub.com/product/openvpn-cookbook-second-edition/9781786463128)" by Jan Just Keijser and the "[Mastering OpenVPN](https://www.packtpub.com/product/mastering-openvpn/9781783553136)" by Eric F. Crist and Jan Just Keijser.

If this feels too much, I would recommend either [OpenVPN Cloud](https://openvpn.net/cloud-vpn/) or [OpenVPN Access Server](https://openvpn.net/access-server/) for you.  OpenVPN Cloud has a free tier, which gives you 3 simultaneously connected devices.  OpenVPN Access Server without any subscription gives you 2 simultaneously connected devices.

I'm closing this ticket as this is not related to a bug, missing feature or otherwise related to misbehaviour or other enhancements of the OpenVPN 3 Linux software.

**Comment by aino-gautam** [comment]
Appreciate the prompt and detailed response. I figured the issue was with an expired certificate on the server and it started working once the issue was fixed.
